DROP INDEX IF EXISTS IDXRecintoID ON ZOO.RECINTO;
DROP INDEX IF EXISTS IDXRecintoNome ON ZOO.RECINTO;
DROP INDEX IF EXISTS IDXFuncionarioNome ON ZOO.PESSOA;
DROP INDEX IF EXISTS IDXFuncionarioDataNascimento ON ZOO.PESSOA;
DROP INDEX IF EXISTS IDXFuncionarioZoo ON ZOO.FUNCIONARIO;
DROP INDEX IF EXISTS IDXFuncionarioSalario ON ZOO.CONTRATO;
DROP INDEX IF EXISTS IDXFuncionarioDataIngresso ON ZOO.FUNCIONARIO;

CREATE INDEX IDXRecintoID ON ZOO.RECINTO(ID);
CREATE INDEX IDXRecintoNome ON ZOO.RECINTO(Nome);
CREATE INDEX IDXFuncionarioNome ON ZOO.PESSOA(Nome);
CREATE INDEX IDXFuncionarioDataNascimento ON ZOO.PESSOA(Data_nascimento);
CREATE INDEX IDXFuncionarioZoo ON ZOO.FUNCIONARIO(Nome_JZ);
CREATE INDEX IDXFuncionarioSalario ON ZOO.CONTRATO(Salario);
CREATE INDEX IDXFuncionarioDataIngresso ON ZOO.FUNCIONARIO(Data_ingresso);