DROP VIEW IF EXISTS ZOO_BILHETES_VENDIDOS_FUNCIONARIO;
GO
CREATE VIEW ZOO_BILHETES_VENDIDOS_FUNCIONARIO AS
    SELECT ZOO.PESSOA.Numero_CC as CC, Nome as Nome, COUNT(ZOO.BILHETE.ID) as bilhetesVendidos
    FROM ZOO.PESSOA
    INNER JOIN ZOO.FUNCIONARIO ON ZOO.PESSOA.Numero_CC = ZOO.FUNCIONARIO.Numero_CC
    INNER JOIN ZOO.BILHETE ON ZOO.FUNCIONARIO.Numero_CC = ZOO.BILHETE.F_Numero_CC
    GROUP BY ZOO.PESSOA.Numero_CC, Nome;
GO

DROP VIEW IF EXISTS ZOO.BILHETES_VENDIDOS_BILHETEIRA;
GO
CREATE VIEW ZOO.BILHETES_VENDIDOS_BILHETEIRA AS
    SELECT Recinto_ID, COUNT(ZOO.BILHETE.ID) as bilhetesVendidos
    FROM ZOO.BILHETEIRA
    INNER JOIN ZOO.BILHETE ON ZOO.BILHETEIRA.Recinto_ID = ZOO.BILHETE.Bilheteira_ID
    GROUP BY Recinto_ID
GO

DROP VIEW IF EXISTS ZOO.ANIMAL_DETALHADO;
GO
CREATE VIEW ZOO.ANIMAL_DETALHADO AS
SELECT ZOO.ANIMAL.ID as AnimalID, 
       ZOO.ANIMAL.Dieta as AnimalDieta, 
       ZOO.ANIMAL.Nome as AnimalNome,
       ZOO.ANIMAL.Especie as AnimalEspecie,
       ZOO.ANIMAL.Cor as AnimalCor,
       ZOO.ANIMAL.Comprimento as AnimalComprimento,
       ZOO.ANIMAL.Peso as AnimalPeso,
       ZOO.ANIMAL.Grupo_Taxonomico as AnimalGrupoTaxonomico,
       ZOO.RECINTO.[Nome] as HabitatNome, 
       ZOO.ANIMAL.Habitaculo_ID as HabitaculoID,
       ZOO.PESSOA.[Nome] as VeterinarioNome
FROM ZOO.ANIMAL 
INNER JOIN ZOO.RECINTO ON ZOO.ANIMAL.Habitat_ID = ZOO.RECINTO.ID
INNER JOIN ZOO.PESSOA ON ZOO.ANIMAL.Veterinario_CC = ZOO.PESSOA.Numero_CC
GO

DROP VIEW IF EXISTS ZOO.FUNCIONARIO_DETALHADO_TOTAL_CONTRATO;
GO 
CREATE VIEW ZOO.FUNCIONARIO_DETALHADO_TOTAL_CONTRATO AS
SELECT FDT.*, C.Tipo_contrato, C.Salario, C.Data_inicio_contrato, C.Data_fim_contrato 
FROM ZOO.FUNCIONARIO_DETALHADO_TOTAL FDT
INNER JOIN ZOO.CONTRATO C ON FDT.Numero_CC = C.F_Numero_CC;
GO 

DROP VIEW IF EXISTS ZOO.FUNCIONARIO_DETALHADO_TOTAL;
GO
CREATE VIEW ZOO.FUNCIONARIO_DETALHADO_TOTAL AS
        SELECT FD.*,
            'GERENTE' as Role
        FROM ZOO.FUNCIONARIO_DETALHADO FD
        INNER JOIN ZOO.GERENTE G ON FD.Numero_CC = G.F_Numero_CC
        WHERE FD.Numero_CC = G.F_Numero_CC
        UNION ALL
        SELECT FD.*,
            'FUNCIONARIO_BILHETEIRA' as Role
        FROM ZOO.FUNCIONARIO_DETALHADO FD
        INNER JOIN ZOO.FUNCIONARIO_BILHETEIRA FB ON FD.Numero_CC = FB.F_Numero_CC
        WHERE FD.Numero_CC = FB.F_Numero_CC
        UNION ALL
        -- Repeat for other roles
        SELECT FD.*,
            'FUNCIONARIO_LIMPEZA' as Role
        FROM ZOO.FUNCIONARIO_DETALHADO FD
        INNER JOIN ZOO.FUNCIONARIO_LIMPEZA FL ON FD.Numero_CC = FL.F_Numero_CC
        WHERE FD.Numero_CC = FL.F_Numero_CC
        UNION ALL
        SELECT FD.*,
            'TRABALHADOR_RESTAURACAO' as Role
        FROM ZOO.FUNCIONARIO_DETALHADO FD
        INNER JOIN ZOO.TRABALHADOR_RESTAURACAO FM ON FD.Numero_CC = FM.F_Numero_CC
        WHERE FD.Numero_CC = FM.F_Numero_CC
        UNION ALL
        SELECT FD.*,
            'SEGURANCA' as Role
        FROM ZOO.FUNCIONARIO_DETALHADO FD
        INNER JOIN ZOO.SEGURANCA FS ON FD.Numero_CC = FS.F_Numero_CC
        WHERE FD.Numero_CC = FS.F_Numero_CC
        UNION ALL
        SELECT FD.*,
            'VETERINARIO' as Role
        FROM ZOO.FUNCIONARIO_DETALHADO FD
        INNER JOIN ZOO.VETERINARIO FV ON FD.Numero_CC = FV.F_Numero_CC
        WHERE FD.Numero_CC = FV.F_Numero_CC
        UNION ALL
        SELECT FD.*,
            'TRATADOR' as Role
        FROM ZOO.FUNCIONARIO_DETALHADO FD
        INNER JOIN ZOO.TRATADOR T ON FD.Numero_CC = T.F_Numero_CC
        WHERE FD.Numero_CC = T.F_Numero_CC;
GO

DROP VIEW IF EXISTS ZOO.FUNCIONARIO_DETALHADO
GO
CREATE VIEW ZOO.FUNCIONARIO_DETALHADO AS
SELECT ZOO.PESSOA.Numero_CC, ZOO.PESSOA.Nome, ZOO.PESSOA.Genero, ZOO.PESSOA.Data_nascimento, ZOO.FUNCIONARIO.Nome_JZ, ZOO.FUNCIONARIO.Num_Funcionario, ZOO.FUNCIONARIO.Data_ingresso FROM ZOO.FUNCIONARIO
INNER JOIN ZOO.PESSOA ON ZOO.FUNCIONARIO.Numero_CC = ZOO.PESSOA.Numero_CC;
GO

DROP VIEW IF EXISTS ZOO.HABITAT_DETALHADO;
GO
CREATE VIEW ZOO.HABITAT_DETALHADO
AS
SELECT ZOO.HABITAT.Recinto_ID, ZOO.HABITAT.Nome_JZ, ZOO.RECINTO.Nome, ZOO.RECINTO.Estado FROM ZOO.HABITAT INNER JOIN ZOO.RECINTO ON ZOO.HABITAT.Recinto_ID = ZOO.RE
GO

DROP VIEW IF EXISTS ZOO.VETERINARIO_DETALHADO;
GO
CREATE VIEW ZOO.VETERINARIO_DETALHADO AS
SELECT * FROM ZOO.VETERINARIO
INNER JOIN ZOO.PESSOA ON ZOO.VETERINARIO.F_Numero_CC = ZOO.PESSOA.Numero_CC;
GO

DROP VIEW IF EXISTS ZOO.BILHETEIRA_DETALHADA;
GO
CREATE VIEW ZOO.BILHETEIRA_DETALHADA AS
SELECT ZOO.RECINTO.*
FROM ZOO.BILHETEIRA INNER JOIN ZOO.RECINTO ON ZOO.BILHETEIRA.Recinto_ID = ZOO.RECINTO.ID AND ZOO.BILHETEIRA.Nome_JZ = ZOO.RECINTO.Nome_JZ
GO

DROP VIEW IF EXISTS ZOO.LIMPA_DETALHADO;
GO
CREATE VIEW ZOO.LIMPA_DETALHADO AS
SELECT R.ID, R.Estado, R.Nome as Nome_Recinto, FD.* FROM ZOO.LIMPA AS L
INNER JOIN ZOO.RECINTO as R ON L.Recinto_ID = R.ID AND L.Nome_JZ = R.Nome_JZ 
INNER JOIN ZOO.FUNCIONARIO_DETALHADO as FD ON L.FL_Numero_CC = FD.Numero_CC;
GO

DROP VIEW IF EXISTS ZOO.RESPONSAVEL_POR_DETALHADO;
GO
CREATE VIEW ZOO.RESPONSAVEL_POR_DETALHADO AS
SELECT R.ID AS RECINTO_ID, R.Nome AS RECINTO_NOME, R.Estado AS RECINTO_ESTADO, FD.* FROM ZOO.RESPONSAVEL_POR AS RP
INNER JOIN ZOO.FUNCIONARIO_DETALHADO AS FD ON RP.T_Numero_CC = FD.Numero_CC
INNER JOIN ZOO.RECINTO AS R ON RP.Habitat_ID = R.ID AND RP.Nome_JZ = R.Nome_JZ;
GO

DROP VIEW IF EXISTS ZOO.TRABALHADOR_RESTAURACAO_DETALHADO;
GO
CREATE VIEW ZOO.TRABALHADOR_RESTAURACAO_DETALHADO AS
SELECT ZOO.RECINTO.ID AS RECINTO_ID, ZOO.RECINTO.Nome AS RECINTO_NOME, ZOO.RECINTO.Estado AS RECINTO_ESTADO, ZOO.FUNCIONARIO_DETALHADO_TOTAL_CONTRATO.* FROM ZOO.TRABALHADOR_RESTAURACAO
INNER JOIN ZOO.FUNCIONARIO_DETALHADO_TOTAL_CONTRATO ON ZOO.TRABALHADOR_RESTAURACAO.F_Numero_CC = ZOO.FUNCIONARIO_DETALHADO_TOTAL_CONTRATO.Numero_CC
INNER JOIN ZOO.RECINTO ON ZOO.TRABALHADOR_RESTAURACAO.Restauracao_ID = ZOO.RECINTO.ID AND ZOO.TRABALHADOR_RESTAURACAO.Nome_JZ = ZOO.RECINTO.Nome_JZ;
GO

DROP VIEW IF EXISTS ZOO.SEGURANCA_DETALHADO;
GO
CREATE VIEW ZOO.SEGURANCA_DETALHADO AS
SELECT ZOO.RECINTO.ID AS RECINTO_ID, ZOO.RECINTO.Nome AS RECINTO_NOME, ZOO.RECINTO.Estado AS RECINTO_ESTADO, ZOO.FUNCIONARIO_DETALHADO_TOTAL_CONTRATO.*, ZOO.SEGURANCA.GerenteSeguranca_Numero FROM ZOO.SEGURANCA
INNER JOIN ZOO.FUNCIONARIO_DETALHADO_TOTAL_CONTRATO ON ZOO.SEGURANCA.F_Numero_CC = ZOO.FUNCIONARIO_DETALHADO_TOTAL_CONTRATO.Numero_CC
INNER JOIN ZOO.RECINTO ON ZOO.SEGURANCA.Recinto_ID = ZOO.RECINTO.ID AND ZOO.SEGURANCA.Nome_JZ = ZOO.RECINTO.Nome_JZ;
GO

DROP VIEW IF EXISTS ZOO.VETERINARIO_DETALHADO;
GO
CREATE VIEW ZOO.VETERINARIO_DETALHADO AS
SELECT * FROM ZOO.VETERINARIO
INNER JOIN ZOO.FUNCIONARIO_DETALHADO ON ZOO.VETERINARIO.F_Numero_CC = ZOO.FUNCIONARIO_DETALHADO.Numero_CC;
GO